### ISSUE TITLE
This is the same repo as the dark theme

### ISSUE THREAD

**Issue by dmuiX** [ceiphr/sn-yaru-light-theme#1]
Hi,

First of all thanks alot for your dark theme. I just love it =)
Actually this repository contains the same as the dark theme. Seems like you haven't developed it so far? 
You have said, that it should be easy to do, so would be pretty amazing if you could make it or correct the link if its just an error. 

thanks ;)

**Comment by ceiphr** [comment]
Thank you!

Correct, I have not gotten to this even though it wouldn't take much time. I can get to work on this Wednesday.

**Comment by ceiphr** [comment]
I've released the first version of the theme!

Here is the installation link: https://changelog.ceiphr.com/p/VGe2xeU6G3

It definitely needs polishing when compared to the original theme. I think I'll be able to make the necessary tweaks sometime this weekend.

Please feel free to report any significant contrast issues or inconsistencies.
